name: kids-site2
services:
  - name: web
    github:
      repo: vip2singh/kids-site2
      branch: main
      deploy_on_push: true
      dir: "web"
    static_site:
      build_command: ""
      output_dir: "web"
      routes:
        - path: "/"
    instance_count: 1
    instance_size_slug: "basic-xxs"
    run_command: null
    envs: []
